'use client';

import { useEffect, useCallback, useState } from 'react';
import { useMaterialReady } from './MaterialProvider';

interface ThemeConfig {
  name: string;
  swatch: string;
  dark: Record<string, string>;
  light: Record<string, string>;
}

const THEMES: ThemeConfig[] = [
  {
    name: 'Expressive Blue',
    swatch: '#1565C0',
    dark: {
      '--md-sys-color-primary': '#a8c7fa',
      '--md-sys-color-on-primary': '#062e6f',
      '--md-sys-color-primary-container': '#234a8c',
      '--md-sys-color-on-primary-container': '#d4e3ff',
      '--md-sys-color-primary-fixed': '#d4e3ff',
      '--md-sys-color-primary-fixed-dim': '#a8c7fa',
      '--md-sys-color-on-primary-fixed': '#001b3d',
      '--md-sys-color-on-primary-fixed-variant': '#234a8c',
      '--md-sys-color-secondary': '#b9c4dc',
      '--md-sys-color-on-secondary': '#243049',
      '--md-sys-color-secondary-container': '#3a4663',
      '--md-sys-color-on-secondary-container': '#d5e0f9',
      '--md-sys-color-secondary-fixed': '#d5e0f9',
      '--md-sys-color-secondary-fixed-dim': '#b9c4dc',
      '--md-sys-color-on-secondary-fixed': '#101c2b',
      '--md-sys-color-on-secondary-fixed-variant': '#3a4663',
      '--md-sys-color-tertiary': '#dfc0e8',
      '--md-sys-color-on-tertiary': '#3a2845',
      '--md-sys-color-tertiary-container': '#523e5d',
      '--md-sys-color-on-tertiary-container': '#fbd7fc',
      '--md-sys-color-tertiary-fixed': '#fbd7fc',
      '--md-sys-color-tertiary-fixed-dim': '#dfc0e8',
      '--md-sys-color-on-tertiary-fixed': '#231231',
      '--md-sys-color-on-tertiary-fixed-variant': '#523e5d',
      '--md-sys-color-error': '#ffb4ab',
      '--md-sys-color-on-error': '#690005',
      '--md-sys-color-error-container': '#93000a',
      '--md-sys-color-on-error-container': '#ffdad6',
      '--md-sys-color-background': '#0e1520',
      '--md-sys-color-on-background': '#dee3ef',
      '--md-sys-color-surface': '#0e1520',
      '--md-sys-color-on-surface': '#dee3ef',
      '--md-sys-color-surface-bright': '#343d4c',
      '--md-sys-color-surface-dim': '#0e1520',
      '--md-sys-color-surface-variant': '#424857',
      '--md-sys-color-on-surface-variant': '#c2c8dc',
      '--md-sys-color-surface-container': '#1b2130',
      '--md-sys-color-surface-container-lowest': '#090f19',
      '--md-sys-color-surface-container-low': '#161c2a',
      '--md-sys-color-surface-container-high': '#262c3b',
      '--md-sys-color-surface-container-highest': '#313748',
      '--md-sys-color-surface-tint': '#a8c7fa',
      '--md-sys-color-outline': '#8c924b',
      '--md-sys-color-outline-variant': '#424857',
      '--md-sys-color-inverse-surface': '#dee3ef',
      '--md-sys-color-inverse-on-surface': '#2a3142',
      '--md-sys-color-inverse-primary': '#0755b5',
      '--md-sys-color-scrim': '#000000',
      '--md-sys-color-shadow': '#000000',
    },
    light: {
      '--md-sys-color-primary': '#0755b5',
      '--md-sys-color-on-primary': '#ffffff',
      '--md-sys-color-primary-container': '#d4e3ff',
      '--md-sys-color-on-primary-container': '#001b3d',
      '--md-sys-color-primary-fixed': '#d4e3ff',
      '--md-sys-color-primary-fixed-dim': '#a8c7fa',
      '--md-sys-color-on-primary-fixed': '#001b3d',
      '--md-sys-color-on-primary-fixed-variant': '#234a8c',
      '--md-sys-color-secondary': '#555f71',
      '--md-sys-color-on-secondary': '#ffffff',
      '--md-sys-color-secondary-container': '#d9e3f8',
      '--md-sys-color-on-secondary-container': '#121c2b',
      '--md-sys-color-secondary-fixed': '#d9e3f8',
      '--md-sys-color-secondary-fixed-dim': '#b9c4dc',
      '--md-sys-color-on-secondary-fixed': '#101c2b',
      '--md-sys-color-on-secondary-fixed-variant': '#3a4663',
      '--md-sys-color-tertiary': '#6b5673',
      '--md-sys-color-on-tertiary': '#ffffff',
      '--md-sys-color-tertiary-container': '#f2daff',
      '--md-sys-color-on-tertiary-container': '#261430',
      '--md-sys-color-tertiary-fixed': '#f2daff',
      '--md-sys-color-tertiary-fixed-dim': '#dfc0e8',
      '--md-sys-color-on-tertiary-fixed': '#231231',
      '--md-sys-color-on-tertiary-fixed-variant': '#523e5d',
      '--md-sys-color-error': '#ba1a1a',
      '--md-sys-color-on-error': '#ffffff',
      '--md-sys-color-error-container': '#ffdad6',
      '--md-sys-color-on-error-container': '#410002',
      '--md-sys-color-background': '#f8f9ff',
      '--md-sys-color-on-background': '#191c20',
      '--md-sys-color-surface': '#f8f9ff',
      '--md-sys-color-on-surface': '#191c20',
      '--md-sys-color-surface-bright': '#f8f9ff',
      '--md-sys-color-surface-dim': '#d8dae0',
      '--md-sys-color-surface-variant': '#dfe2eb',
      '--md-sys-color-on-surface-variant': '#43474e',
      '--md-sys-color-surface-container': '#eceef4',
      '--md-sys-color-surface-container-lowest': '#ffffff',
      '--md-sys-color-surface-container-low': '#f2f3fa',
      '--md-sys-color-surface-container-high': '#e6e8ee',
      '--md-sys-color-surface-container-highest': '#e1e2e8',
      '--md-sys-color-surface-tint': '#0755b5',
      '--md-sys-color-outline': '#74777f',
      '--md-sys-color-outline-variant': '#c4c6d0',
      '--md-sys-color-inverse-surface': '#2e3036',
      '--md-sys-color-inverse-on-surface': '#eff0f7',
      '--md-sys-color-inverse-primary': '#a8c7fa',
      '--md-sys-color-scrim': '#000000',
      '--md-sys-color-shadow': '#000000',
    },
  },
  {
    name: 'Vibrant Pink',
    swatch: '#C2185B',
    dark: {
      '--md-sys-color-primary': '#ffb1c8',
      '--md-sys-color-on-primary': '#670038',
      '--md-sys-color-primary-container': '#8e1a50',
      '--md-sys-color-on-primary-container': '#ffd9e4',
      '--md-sys-color-primary-fixed': '#ffd9e4',
      '--md-sys-color-primary-fixed-dim': '#ffb1c8',
      '--md-sys-color-on-primary-fixed': '#3d001e',
      '--md-sys-color-on-primary-fixed-variant': '#8e1a50',
      '--md-sys-color-secondary': '#e4bdbd',
      '--md-sys-color-on-secondary': '#4a2525',
      '--md-sys-color-secondary-container': '#633b3b',
      '--md-sys-color-on-secondary-container': '#ffd7d7',
      '--md-sys-color-secondary-fixed': '#ffd7d7',
      '--md-sys-color-secondary-fixed-dim': '#e4bdbd',
      '--md-sys-color-on-secondary-fixed': '#321313',
      '--md-sys-color-on-secondary-fixed-variant': '#633b3b',
      '--md-sys-color-tertiary': '#f0b8c8',
      '--md-sys-color-on-tertiary': '#4a2535',
      '--md-sys-color-tertiary-container': '#633b4b',
      '--md-sys-color-on-tertiary-container': '#fdd7e4',
      '--md-sys-color-tertiary-fixed': '#fdd7e4',
      '--md-sys-color-tertiary-fixed-dim': '#f0b8c8',
      '--md-sys-color-on-tertiary-fixed': '#32111e',
      '--md-sys-color-on-tertiary-fixed-variant': '#633b4b',
      '--md-sys-color-error': '#ffb4ab',
      '--md-sys-color-on-error': '#690005',
      '--md-sys-color-error-container': '#93000a',
      '--md-sys-color-on-error-container': '#ffdad6',
      '--md-sys-color-background': '#1a1114',
      '--md-sys-color-on-background': '#f0dee1',
      '--md-sys-color-surface': '#1a1114',
      '--md-sys-color-on-surface': '#f0dee1',
      '--md-sys-color-surface-bright': '#372d2f',
      '--md-sys-color-surface-dim': '#1a1114',
      '--md-sys-color-surface-variant': '#524345',
      '--md-sys-color-on-surface-variant': '#d6c1c4',
      '--md-sys-color-surface-container': '#2e2225',
      '--md-sys-color-surface-container-lowest': '#140c0e',
      '--md-sys-color-surface-container-low': '#221a1c',
      '--md-sys-color-surface-container-high': '#392d2f',
      '--md-sys-color-surface-container-highest': '#443839',
      '--md-sys-color-surface-tint': '#ffb1c8',
      '--md-sys-color-outline': '#9e8c8f',
      '--md-sys-color-outline-variant': '#524345',
      '--md-sys-color-inverse-surface': '#f0dee1',
      '--md-sys-color-inverse-on-surface': '#372d2f',
      '--md-sys-color-inverse-primary': '#a82d57',
      '--md-sys-color-scrim': '#000000',
      '--md-sys-color-shadow': '#000000',
    },
    light: {
      '--md-sys-color-primary': '#a82d57',
      '--md-sys-color-on-primary': '#ffffff',
      '--md-sys-color-primary-container': '#ffd9e4',
      '--md-sys-color-on-primary-container': '#3d001e',
      '--md-sys-color-primary-fixed': '#ffd9e4',
      '--md-sys-color-primary-fixed-dim': '#ffb1c8',
      '--md-sys-color-on-primary-fixed': '#3d001e',
      '--md-sys-color-on-primary-fixed-variant': '#8e1a50',
      '--md-sys-color-secondary': '#775656',
      '--md-sys-color-on-secondary': '#ffffff',
      '--md-sys-color-secondary-container': '#ffd7d7',
      '--md-sys-color-on-secondary-container': '#2c1515',
      '--md-sys-color-secondary-fixed': '#ffd7d7',
      '--md-sys-color-secondary-fixed-dim': '#e4bdbd',
      '--md-sys-color-on-secondary-fixed': '#321313',
      '--md-sys-color-on-secondary-fixed-variant': '#633b3b',
      '--md-sys-color-tertiary': '#76565e',
      '--md-sys-color-on-tertiary': '#ffffff',
      '--md-sys-color-tertiary-container': '#fdd7e4',
      '--md-sys-color-on-tertiary-container': '#32111e',
      '--md-sys-color-tertiary-fixed': '#fdd7e4',
      '--md-sys-color-tertiary-fixed-dim': '#f0b8c8',
      '--md-sys-color-on-tertiary-fixed': '#32111e',
      '--md-sys-color-on-tertiary-fixed-variant': '#633b4b',
      '--md-sys-color-error': '#ba1a1a',
      '--md-sys-color-on-error': '#ffffff',
      '--md-sys-color-error-container': '#ffdad6',
      '--md-sys-color-on-error-container': '#410002',
      '--md-sys-color-background': '#fff8f7',
      '--md-sys-color-on-background': '#22191b',
      '--md-sys-color-surface': '#fff8f7',
      '--md-sys-color-on-surface': '#22191b',
      '--md-sys-color-surface-bright': '#fff8f7',
      '--md-sys-color-surface-dim': '#e3d6d8',
      '--md-sys-color-surface-variant': '#f4dce0',
      '--md-sys-color-on-surface-variant': '#524345',
      '--md-sys-color-surface-container': '#f8ebed',
      '--md-sys-color-surface-container-lowest': '#ffffff',
      '--md-sys-color-surface-container-low': '#fef0f2',
      '--md-sys-color-surface-container-high': '#f2eaeb',
      '--md-sys-color-surface-container-highest': '#ede4e6',
      '--md-sys-color-surface-tint': '#a82d57',
      '--md-sys-color-outline': '#857376',
      '--md-sys-color-outline-variant': '#d6c1c4',
      '--md-sys-color-inverse-surface': '#382e2f',
      '--md-sys-color-inverse-on-surface': '#fdecee',
      '--md-sys-color-inverse-primary': '#ffb1c8',
      '--md-sys-color-scrim': '#000000',
      '--md-sys-color-shadow': '#000000',
    },
  },
  {
    name: 'Lush Green',
    swatch: '#2E7D32',
    dark: {
      '--md-sys-color-primary': '#8fd89a',
      '--md-sys-color-on-primary': '#00390e',
      '--md-sys-color-primary-container': '#005318',
      '--md-sys-color-on-primary-container': '#abf5b4',
      '--md-sys-color-primary-fixed': '#abf5b4',
      '--md-sys-color-primary-fixed-dim': '#8fd89a',
      '--md-sys-color-on-primary-fixed': '#002205',
      '--md-sys-color-on-primary-fixed-variant': '#005318',
      '--md-sys-color-secondary': '#b3ccb3',
      '--md-sys-color-on-secondary': '#1f361f',
      '--md-sys-color-secondary-container': '#354d35',
      '--md-sys-color-on-secondary-container': '#cfe8cf',
      '--md-sys-color-secondary-fixed': '#cfe8cf',
      '--md-sys-color-secondary-fixed-dim': '#b3ccb3',
      '--md-sys-color-on-secondary-fixed': '#0b1f0b',
      '--md-sys-color-on-secondary-fixed-variant': '#354d35',
      '--md-sys-color-tertiary': '#a2d0cb',
      '--md-sys-color-on-tertiary': '#003735',
      '--md-sys-color-tertiary-container': '#004f4c',
      '--md-sys-color-on-tertiary-container': '#beece7',
      '--md-sys-color-tertiary-fixed': '#beece7',
      '--md-sys-color-tertiary-fixed-dim': '#a2d0cb',
      '--md-sys-color-on-tertiary-fixed': '#00201e',
      '--md-sys-color-on-tertiary-fixed-variant': '#004f4c',
      '--md-sys-color-error': '#ffb4ab',
      '--md-sys-color-on-error': '#690005',
      '--md-sys-color-error-container': '#93000a',
      '--md-sys-color-on-error-container': '#ffdad6',
      '--md-sys-color-background': '#111a12',
      '--md-sys-color-on-background': '#e0e3dd',
      '--md-sys-color-surface': '#111a12',
      '--md-sys-color-on-surface': '#e0e3dd',
      '--md-sys-color-surface-bright': '#373f37',
      '--md-sys-color-surface-dim': '#111a12',
      '--md-sys-color-surface-variant': '#414941',
      '--md-sys-color-on-surface-variant': '#c1c9c0',
      '--md-sys-color-surface-container': '#262e26',
      '--md-sys-color-surface-container-lowest': '#0c140d',
      '--md-sys-color-surface-container-low': '#1a2219',
      '--md-sys-color-surface-container-high': '#313931',
      '--md-sys-color-surface-container-highest': '#3c443c',
      '--md-sys-color-surface-tint': '#8fd89a',
      '--md-sys-color-outline': '#8b938a',
      '--md-sys-color-outline-variant': '#414941',
      '--md-sys-color-inverse-surface': '#e0e3dd',
      '--md-sys-color-inverse-on-surface': '#2b322c',
      '--md-sys-color-inverse-primary': '#006e24',
      '--md-sys-color-scrim': '#000000',
      '--md-sys-color-shadow': '#000000',
    },
    light: {
      '--md-sys-color-primary': '#006e24',
      '--md-sys-color-on-primary': '#ffffff',
      '--md-sys-color-primary-container': '#abf5b4',
      '--md-sys-color-on-primary-container': '#002205',
      '--md-sys-color-primary-fixed': '#abf5b4',
      '--md-sys-color-primary-fixed-dim': '#8fd89a',
      '--md-sys-color-on-primary-fixed': '#002205',
      '--md-sys-color-on-primary-fixed-variant': '#005318',
      '--md-sys-color-secondary': '#516350',
      '--md-sys-color-on-secondary': '#ffffff',
      '--md-sys-color-secondary-container': '#cfe8cf',
      '--md-sys-color-on-secondary-container': '#0f1f10',
      '--md-sys-color-secondary-fixed': '#cfe8cf',
      '--md-sys-color-secondary-fixed-dim': '#b3ccb3',
      '--md-sys-color-on-secondary-fixed': '#0b1f0b',
      '--md-sys-color-on-secondary-fixed-variant': '#354d35',
      '--md-sys-color-tertiary': '#396561',
      '--md-sys-color-on-tertiary': '#ffffff',
      '--md-sys-color-tertiary-container': '#beece7',
      '--md-sys-color-on-tertiary-container': '#00201e',
      '--md-sys-color-tertiary-fixed': '#beece7',
      '--md-sys-color-tertiary-fixed-dim': '#a2d0cb',
      '--md-sys-color-on-tertiary-fixed': '#00201e',
      '--md-sys-color-on-tertiary-fixed-variant': '#004f4c',
      '--md-sys-color-error': '#ba1a1a',
      '--md-sys-color-on-error': '#ffffff',
      '--md-sys-color-error-container': '#ffdad6',
      '--md-sys-color-on-error-container': '#410002',
      '--md-sys-color-background': '#fcfdf6',
      '--md-sys-color-on-background': '#1a1c18',
      '--md-sys-color-surface': '#fcfdf6',
      '--md-sys-color-on-surface': '#1a1c18',
      '--md-sys-color-surface-bright': '#fcfdf6',
      '--md-sys-color-surface-dim': '#dbdcd5',
      '--md-sys-color-surface-variant': '#dfe5d8',
      '--md-sys-color-on-surface-variant': '#414941',
      '--md-sys-color-surface-container': '#eeeef0',
      '--md-sys-color-surface-container-lowest': '#ffffff',
      '--md-sys-color-surface-container-low': '#f7f8f1',
      '--md-sys-color-surface-container-high': '#e8e9e2',
      '--md-sys-color-surface-container-highest': '#e2e3dd',
      '--md-sys-color-surface-tint': '#006e24',
      '--md-sys-color-outline': '#727970',
      '--md-sys-color-outline-variant': '#c1c9c0',
      '--md-sys-color-inverse-surface': '#2f312c',
      '--md-sys-color-inverse-on-surface': '#f0f1eb',
      '--md-sys-color-inverse-primary': '#8fd89a',
      '--md-sys-color-scrim': '#000000',
      '--md-sys-color-shadow': '#000000',
    },
  },
  {
    name: 'Expressive Purple',
    swatch: '#7B1FA2',
    dark: {
      '--md-sys-color-primary': '#d4bbff',
      '--md-sys-color-on-primary': '#4a0080',
      '--md-sys-color-primary-container': '#6700a9',
      '--md-sys-color-on-primary-container': '#ecdcff',
      '--md-sys-color-primary-fixed': '#ecdcff',
      '--md-sys-color-primary-fixed-dim': '#d4bbff',
      '--md-sys-color-on-primary-fixed': '#2a004b',
      '--md-sys-color-on-primary-fixed-variant': '#6700a9',
      '--md-sys-color-secondary': '#cfc0dc',
      '--md-sys-color-on-secondary': '#352a41',
      '--md-sys-color-secondary-container': '#4c4058',
      '--md-sys-color-on-secondary-container': '#ebddf8',
      '--md-sys-color-secondary-fixed': '#ebddf8',
      '--md-sys-color-secondary-fixed-dim': '#cfc0dc',
      '--md-sys-color-on-secondary-fixed': '#21152e',
      '--md-sys-color-on-secondary-fixed-variant': '#4c4058',
      '--md-sys-color-tertiary': '#f0b8c8',
      '--md-sys-color-on-tertiary': '#4a2535',
      '--md-sys-color-tertiary-container': '#633b4b',
      '--md-sys-color-on-tertiary-container': '#fdd7e4',
      '--md-sys-color-tertiary-fixed': '#fdd7e4',
      '--md-sys-color-tertiary-fixed-dim': '#f0b8c8',
      '--md-sys-color-on-tertiary-fixed': '#32111e',
      '--md-sys-color-on-tertiary-fixed-variant': '#633b4b',
      '--md-sys-color-error': '#ffb4ab',
      '--md-sys-color-on-error': '#690005',
      '--md-sys-color-error-container': '#93000a',
      '--md-sys-color-on-error-container': '#ffdad6',
      '--md-sys-color-background': '#151218',
      '--md-sys-color-on-background': '#e6e0e8',
      '--md-sys-color-surface': '#151218',
      '--md-sys-color-on-surface': '#e6e0e8',
      '--md-sys-color-surface-bright': '#3b373c',
      '--md-sys-color-surface-dim': '#151218',
      '--md-sys-color-surface-variant': '#4a454c',
      '--md-sys-color-on-surface-variant': '#cbc4cf',
      '--md-sys-color-surface-container': '#2d292e',
      '--md-sys-color-surface-container-lowest': '#100d12',
      '--md-sys-color-surface-container-low': '#201c21',
      '--md-sys-color-surface-container-high': '#383339',
      '--md-sys-color-surface-container-highest': '#433e44',
      '--md-sys-color-surface-tint': '#d4bbff',
      '--md-sys-color-outline': '#948f99',
      '--md-sys-color-outline-variant': '#4a454c',
      '--md-sys-color-inverse-surface': '#e6e0e8',
      '--md-sys-color-inverse-on-surface': '#312f35',
      '--md-sys-color-inverse-primary': '#8c25d7',
      '--md-sys-color-scrim': '#000000',
      '--md-sys-color-shadow': '#000000',
    },
    light: {
      '--md-sys-color-primary': '#8c25d7',
      '--md-sys-color-on-primary': '#ffffff',
      '--md-sys-color-primary-container': '#ecdcff',
      '--md-sys-color-on-primary-container': '#2a004b',
      '--md-sys-color-primary-fixed': '#ecdcff',
      '--md-sys-color-primary-fixed-dim': '#d4bbff',
      '--md-sys-color-on-primary-fixed': '#2a004b',
      '--md-sys-color-on-primary-fixed-variant': '#6700a9',
      '--md-sys-color-secondary': '#635b70',
      '--md-sys-color-on-secondary': '#ffffff',
      '--md-sys-color-secondary-container': '#ebddf8',
      '--md-sys-color-on-secondary-container': '#20162b',
      '--md-sys-color-secondary-fixed': '#ebddf8',
      '--md-sys-color-secondary-fixed-dim': '#cfc0dc',
      '--md-sys-color-on-secondary-fixed': '#21152e',
      '--md-sys-color-on-secondary-fixed-variant': '#4c4058',
      '--md-sys-color-tertiary': '#76565e',
      '--md-sys-color-on-tertiary': '#ffffff',
      '--md-sys-color-tertiary-container': '#fdd7e4',
      '--md-sys-color-on-tertiary-container': '#32111e',
      '--md-sys-color-tertiary-fixed': '#fdd7e4',
      '--md-sys-color-tertiary-fixed-dim': '#f0b8c8',
      '--md-sys-color-on-tertiary-fixed': '#32111e',
      '--md-sys-color-on-tertiary-fixed-variant': '#633b4b',
      '--md-sys-color-error': '#ba1a1a',
      '--md-sys-color-on-error': '#ffffff',
      '--md-sys-color-error-container': '#ffdad6',
      '--md-sys-color-on-error-container': '#410002',
      '--md-sys-color-background': '#fffbff',
      '--md-sys-color-on-background': '#1d1a20',
      '--md-sys-color-surface': '#fffbff',
      '--md-sys-color-on-surface': '#1d1a20',
      '--md-sys-color-surface-bright': '#fffbff',
      '--md-sys-color-surface-dim': '#ddd8de',
      '--md-sys-color-surface-variant': '#e4e0ea',
      '--md-sys-color-on-surface-variant': '#4a454c',
      '--md-sys-color-surface-container': '#f0ecf3',
      '--md-sys-color-surface-container-lowest': '#ffffff',
      '--md-sys-color-surface-container-low': '#faf6fc',
      '--md-sys-color-surface-container-high': '#eae6ed',
      '--md-sys-color-surface-container-highest': '#e4e0e8',
      '--md-sys-color-surface-tint': '#8c25d7',
      '--md-sys-color-outline': '#7b7580',
      '--md-sys-color-outline-variant': '#cbc4cf',
      '--md-sys-color-inverse-surface': '#322f35',
      '--md-sys-color-inverse-on-surface': '#f5eff7',
      '--md-sys-color-inverse-primary': '#d4bbff',
      '--md-sys-color-scrim': '#000000',
      '--md-sys-color-shadow': '#000000',
    },
  },
  {
    name: 'Warm Amber',
    swatch: '#E65100',
    dark: {
      '--md-sys-color-primary': '#ffb785',
      '--md-sys-color-on-primary': '#542200',
      '--md-sys-color-primary-container': '#783300',
      '--md-sys-color-on-primary-container': '#ffdbc8',
      '--md-sys-color-primary-fixed': '#ffdbc8',
      '--md-sys-color-primary-fixed-dim': '#ffb785',
      '--md-sys-color-on-primary-fixed': '#331100',
      '--md-sys-color-on-primary-fixed-variant': '#783300',
      '--md-sys-color-secondary': '#e5bfa5',
      '--md-sys-color-on-secondary': '#442a15',
      '--md-sys-color-secondary-container': '#5d402c',
      '--md-sys-color-on-secondary-container': '#ffd8bc',
      '--md-sys-color-secondary-fixed': '#ffd8bc',
      '--md-sys-color-secondary-fixed-dim': '#e5bfa5',
      '--md-sys-color-on-secondary-fixed': '#2e1506',
      '--md-sys-color-on-secondary-fixed-variant': '#5d402c',
      '--md-sys-color-tertiary': '#d0c68c',
      '--md-sys-color-on-tertiary': '#353100',
      '--md-sys-color-tertiary-container': '#4c4824',
      '--md-sys-color-on-tertiary-container': '#ece2a6',
      '--md-sys-color-tertiary-fixed': '#ece2a6',
      '--md-sys-color-tertiary-fixed-dim': '#d0c68c',
      '--md-sys-color-on-tertiary-fixed': '#201d00',
      '--md-sys-color-on-tertiary-fixed-variant': '#4c4824',
      '--md-sys-color-error': '#ffb4ab',
      '--md-sys-color-on-error': '#690005',
      '--md-sys-color-error-container': '#93000a',
      '--md-sys-color-on-error-container': '#ffdad6',
      '--md-sys-color-background': '#1a110c',
      '--md-sys-color-on-background': '#f0dfd5',
      '--md-sys-color-surface': '#1a110c',
      '--md-sys-color-on-surface': '#f0dfd5',
      '--md-sys-color-surface-bright': '#3d332b',
      '--md-sys-color-surface-dim': '#1a110c',
      '--md-sys-color-surface-variant': '#51443a',
      '--md-sys-color-on-surface-variant': '#d4c3b7',
      '--md-sys-color-surface-container': '#2e241e',
      '--md-sys-color-surface-container-lowest': '#140c07',
      '--md-sys-color-surface-container-low': '#231a14',
      '--md-sys-color-surface-container-high': '#392f28',
      '--md-sys-color-surface-container-highest': '#443a32',
      '--md-sys-color-surface-tint': '#ffb785',
      '--md-sys-color-outline': '#9d8e82',
      '--md-sys-color-outline-variant': '#51443a',
      '--md-sys-color-inverse-surface': '#f0dfd5',
      '--md-sys-color-inverse-on-surface': '#362f28',
      '--md-sys-color-inverse-primary': '#994b10',
      '--md-sys-color-scrim': '#000000',
      '--md-sys-color-shadow': '#000000',
    },
    light: {
      '--md-sys-color-primary': '#994b10',
      '--md-sys-color-on-primary': '#ffffff',
      '--md-sys-color-primary-container': '#ffdbc8',
      '--md-sys-color-on-primary-container': '#331100',
      '--md-sys-color-primary-fixed': '#ffdbc8',
      '--md-sys-color-primary-fixed-dim': '#ffb785',
      '--md-sys-color-on-primary-fixed': '#331100',
      '--md-sys-color-on-primary-fixed-variant': '#783300',
      '--md-sys-color-secondary': '#755846',
      '--md-sys-color-on-secondary': '#ffffff',
      '--md-sys-color-secondary-container': '#ffd8bc',
      '--md-sys-color-on-secondary-container': '#2c1506',
      '--md-sys-color-secondary-fixed': '#ffd8bc',
      '--md-sys-color-secondary-fixed-dim': '#e5bfa5',
      '--md-sys-color-on-secondary-fixed': '#2e1506',
      '--md-sys-color-on-secondary-fixed-variant': '#5d402c',
      '--md-sys-color-tertiary': '#5c5e2e',
      '--md-sys-color-on-tertiary': '#ffffff',
      '--md-sys-color-tertiary-container': '#ece2a6',
      '--md-sys-color-on-tertiary-container': '#201d00',
      '--md-sys-color-tertiary-fixed': '#ece2a6',
      '--md-sys-color-tertiary-fixed-dim': '#d0c68c',
      '--md-sys-color-on-tertiary-fixed': '#201d00',
      '--md-sys-color-on-tertiary-fixed-variant': '#4c4824',
      '--md-sys-color-error': '#ba1a1a',
      '--md-sys-color-on-error': '#ffffff',
      '--md-sys-color-error-container': '#ffdad6',
      '--md-sys-color-on-error-container': '#410002',
      '--md-sys-color-background': '#fff8f5',
      '--md-sys-color-on-background': '#211a14',
      '--md-sys-color-surface': '#fff8f5',
      '--md-sys-color-on-surface': '#211a14',
      '--md-sys-color-surface-bright': '#fff8f5',
      '--md-sys-color-surface-dim': '#e3d8cf',
      '--md-sys-color-surface-variant': '#f2dfe4',
      '--md-sys-color-on-surface-variant': '#51443a',
      '--md-sys-color-surface-container': '#f7ece4',
      '--md-sys-color-surface-container-lowest': '#ffffff',
      '--md-sys-color-surface-container-low': '#fef4ec',
      '--md-sys-color-surface-container-high': '#f1e6de',
      '--md-sys-color-surface-container-highest': '#ebe0d8',
      '--md-sys-color-surface-tint': '#994b10',
      '--md-sys-color-outline': '#847469',
      '--md-sys-color-outline-variant': '#d6c3b7',
      '--md-sys-color-inverse-surface': '#372f28',
      '--md-sys-color-inverse-on-surface': '#faeee6',
      '--md-sys-color-inverse-primary': '#ffb785',
      '--md-sys-color-scrim': '#000000',
      '--md-sys-color-shadow': '#000000',
    },
  },
];

function applyTokens(tokens: Record<string, string>) {
  const root = document.documentElement;
  for (const [key, value] of Object.entries(tokens)) {
    root.style.setProperty(key, value);
  }
}

export function ThemePicker() {
  const ready = useMaterialReady();
  const [activeTheme, setActiveTheme] = useState(0);
  const [isDark, setIsDark] = useState(true);

  useEffect(() => {
    if (ready) {
      const scheme = isDark ? THEMES[activeTheme].dark : THEMES[activeTheme].light;
      applyTokens(scheme);
    }
  }, [ready, activeTheme, isDark]);

  if (!ready) return null;

  return (
    <div className="theme-picker">
      {THEMES.map((theme, i) => (
        <button
          key={theme.name}
          className={`theme-swatch ${i === activeTheme ? 'active' : ''}`}
          style={{ background: theme.swatch }}
          onClick={() => setActiveTheme(i)}
          title={theme.name}
          aria-label={`Switch to ${theme.name} theme`}
        />
      ))}
      <div className="dark-light-toggle">
        <md-icon-button
          onClick={() => setIsDark(prev => !prev)}
          aria-label={isDark ? 'Switch to light mode' : 'Switch to dark mode'}
        >
          <md-icon>{isDark ? 'light_mode' : 'dark_mode'}</md-icon>
        </md-icon-button>
      </div>
    </div>
  );
}
